# Inspriation from: https://dev.to/karanpratapsingh/dockerize-your-react-app-4j2e

## Builder Image
FROM node AS builder
ENV NODE_ENV production
# Add a work directory
WORKDIR /app
# Cache and Install dependencies
COPY package.json .
COPY yarn.lock .
RUN yarn config set network-timeout 300000
RUN yarn install --production
# Copy app files
COPY . .
# Build the app
RUN yarn build

## Production Image
# Bundle static assets with nginx
FROM nginx as production
ENV NODE_ENV production
# Copy built assets from builder
COPY --from=builder /app/build /usr/share/nginx/html
# Add your nginx.conf
COPY nginx.conf /etc/nginx/conf.d/default.conf
# Expose port
EXPOSE 80
# Start nginx
CMD ["nginx", "-g", "daemon off;"]