# base image  
FROM python 
# setup environment variable  
ENV DockerHOME=/home/app/webapp  

# set work directory  
RUN mkdir -p $DockerHOME  

# where your code lives  
WORKDIR $DockerHOME  

# set environment variables  
ENV PYTHONDONTWRITEBYTECODE 1
ENV PYTHONUNBUFFERED 1  

# Upgrade Pip
RUN pip install --upgrade pip  

# copy whole project to your docker home directory. 
COPY . $DockerHOME  

# Ensure there are permissions to build and run the backend scripts
RUN /bin/bash -c 'chmod 775 ./setup_env.sh'
RUN /bin/bash -c 'chmod 775 ./build_backend.sh'
RUN /bin/bash -c 'chmod 775 ./run_backend.sh'

# Build the backend incase there are new migrations
RUN /bin/bash -c './setup_env.sh'

# port where the Django app runs  
EXPOSE 81

# build & start server when image is run
CMD ["/bin/bash", "-c", "'./build_backend.sh' && ./run_backend.sh"]
