version: '3.9'

services: 

  backend:
    image: dinnerparty-backend:prod
    build:
      context: backend/
    ports: 
      - "81:81"

  frontend:
    image: dinnerparty-frontend:prod
    build:
      context: frontend/
      target: production
    ports:
      - "80:80"